# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
    config.vm.define "maquina_1" do |vb1|
        vb1.vm.box = "ubuntu/bionic64"
        vb1.vm.network :private_network, ip: "10.0.0.10"
        vb1.vm.hostname = "vm-ansible-master"

    end
    
    config.vm.define "maquina_2" do |vb2|
        vb2.vm.box = "ubuntu/bionic64"
        vb2.vm.network :private_network, ip: "10.0.0.11"
        vb2.vm.hostname = "vm-consul-server"
    end

    config.vm.define "maquina_3" do |vb3|
        vb3.vm.box = "ubuntu/bionic64"
        vb3.vm.network :private_network, ip: "10.0.0.12"
        vb3.vm.hostname = "vm-consul-client"
    end
    
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"      
    end
end