# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
    config.vm.define "maquina_1" do |vb1|
        vb1.vm.box = "ubuntu/bionic64"
        vb1.vm.network :private_network, ip: "10.0.0.10"
        vb1.vm.hostname = "vm-master"

    end
    
    config.vm.define "maquina_2" do |vb2|
        vb2.vm.box = "ubuntu/bionic64"
        vb2.vm.network :private_network, ip: "10.0.0.11"
        vb2.vm.hostname = "vm-worker"
    end

    config.vagrant.plugins = "vagrant-docker-compose"
    config.vm.provision :docker
    config.vm.provision :docker_compose
    

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"    

    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt install git-all
        sudo service docker start
        
    SHELL
      
    end
end